googledatastudio/ds-data-registry

organizations/socrata.json
sources/socrata.json

- Adding Socrata Organization
- Adding Socrata Source

add Socrata organization, add Socrata source

---

categories.json
organizations/twilio.json
sources/twilio.json

Did not run "npm install && npm run prettier", as it seems to add changes to many existing files. Can raise a PR alone for that, if needed.

Added twilio source and organization.

---

organizations/page_modified.json
sources/page_modified.json

Adding the Source JSON file and Organization JSON file for Page Modified to the Google Data Studio ds-data-registry repo.

Page Modified Source and Organization JSON files

---

organizations/firefly_e.json
sources/ebeetask.json

Included ebeetask source and firefly-e organization for ebeetask connector

Included ebeetask source and firefly-e organization for ebeetask connector

---

.gitignore
sources/google_attribution.json
sources/google_dbm.json
sources/google_dcm.json
sources/google_dfp.json
sources/google_ds.json
sources/google_search_console.json
sources/youtube_analytics.json

updated the datastudio gallery URLs to the correct location

updating urls

---

organizations/callrail.json
sources/callrail.json

Adding a data source for CallRail, https://callrail.com/

Add CallRail info

---

organizations/toky.json
sources/toky_api.json
sources/toky_call_data.json

Pull request for Toky API as Data Studio source

Added Toky

---

organizations/sig.json
sources/sig_etl.json

Creating Soluciones Informaticas Globales SA organization and SIG_ETL source

new organization and source for Google DataStudio connectors

---

organizations/capsule.json
sources/capsule.json

Add [Capsule](https://capsulecrm.com) as an organisation and source.

Add Capsule as organisation and source

---

organizations/trackonomics.json
sources/trackonomics.json

Please add Trackonomics as a data source and organization.
I opened this pull request again under this account to be able to pass the cla bot check.
I closed the other pull request of course.

Add Trackonomics as organization and as source

---

organizations/gamesvid.json
organizations/quantum.json
organizations/youappi.json
organizations/zeropark.json
sources/comparer.json
sources/gamesvid.json
sources/quantum.json
sources/youappi.json
sources/zeropark.json

Add ZeroPark, GamesVid, Comparer, Quantum, YouAppi

---

organizations/hivewyre.json
sources/hivewyre.json
sources/yandex_market.json

Add Yandex.Market & Hivewyre

---

organizations/phonewagon.json
organizations/reshift_digital.json
sources/phonewagon.json

Added 
PhoneWagon Inc. to Organizations
and PhonWagon API to Sources

Added PhoneWagon Source and Organization

---

organizations/digimind.json
sources/digimind.json

Adding the source/organaziation for the Digimind connector.

Add digimind to organizations/sources

---

organizations/avidtrak.json
sources/avidtrak.json

For creating Google Data Studio Connector

Add source/organisation for AvidTrak GDS Connector

---

organizations/iugu.json
organizations/pagseguro.json
organizations/wirecard.json
sources/iugu.json
sources/pagseguro.json
sources/wirecard.json

Add source/organization for iugu and PagSeguro payments

Added Iugu, PagSeguro and Wirecard payments

---

organizations/jivox.json
organizations/rtbiq.json
organizations/verve.json
sources/centro_dsp.json
sources/jivox.json
sources/jumptap.json
sources/rtbiq.json
sources/verve_velocity.json

Files Added.
**Organizations:** 
1. jivox.json
2. rtbiq.json
3. verve.json
**Sources:** 
1. cento_dsp.json
2. jivox.json
3. jumptap.json
4. rtbiq.json
5. verve_velocity.json

Files added for Tapclicks Connectors

---

organizations/amalytix.json
sources/amalytix.json

- Added "Amalytix" as a new organization and source
- Executed prettier

Add Amalytix

---

organizations/qooqie.json
sources/qooqie.json

This time creating pull request with the user who signed the CLA

Added files for Qooqie organization

---

organizations/integromat.json
sources/integromat.json

Integromat connector, available [here](https://www.integromat.com/cs/integrations/google-data-studio).
Hi, thank you in advance for merging the PR!

Add Integromat to organizations/sources

---

organizations/intuit.json
sources/quickbooks_online.json

- added intuit organization
- added quickbooks online source

Intuit quickbooks source and appropriate organization added

---

organizations/integratouch.json
sources/integratouch.json
sources/symphony.json

Resubmitting PR with corrected authorship, 
Adding integratouch.json and symphony.json to source

Adding integratouch.json and symphony.json to source

---

organizations/pokeapi.json
sources/pokeapi.json

Gotta catch them all! All the connectors . . .

Added PokeAPI data source

---

.gitignore
organizations/linkfluence.json
sources/radarly_analytics.json

add Linkfluence as orgainzation & radarly analytics as source

add Linkfluence as orgainzation & radarly analytics as source

---

organizations/bitrix24.json
sources/bitrix24.json

Add Bitrix24 organization

---

organizations/omolds.json
sources/sitom.json

Subiendo Archivos desde local a Repo en GITHUB

Subiendo Archivos

---

organizations/rankwatch.json

Add RankWatch as an organization

---

sources/rankwatch.json

Please Add the above data source!

Added RankWatch Source for GDS Connector

---

organizations/socialbakers.json
sources/socialbakers.json

Added organization and source for Socialbakers

Socialbakers

---

organizations/fyle.json
sources/fyle.json

Fyle (https://www.fylehq.com) is an expense management product. This data source will enable Fyle users to analyze their expense data.

Fyle as a data source

---

organizations/prestashop.json
sources/prestashop.json

Source and organization for PrestaShop connector

Add PrestaShop source and organization

---

categories.json
organizations/strava.json
sources/strava.json

Adding "Strava" as source and organization, adding "sports" as category

Strava Connector

---

organizations/rank_ranger.json
sources/rank_ranger.json

Organization and Source for Rank Ranger Campaign Stats connector

Create Rank Ranger Organization and Source

---

organizations/oncrawl.json
sources/oncrawl.json

Add OnCrawl Organization and source

---

organizations/paycall.json
sources/paycall.json

Added the organization 'paycall' and adding paycall to the sources.
I did it because i need to add paycall to the sources in the manifest file in my google data connector

Add support for paycall!

---

organizations/whiterabbit.json

White Rabbit is a saas provider of a Customer Data Platform and marketing automation software.
https://www.whiterabbitsuite.com/

Add Organization White Rabbit

---

sources/whiterabbit.json

White Rabbit is a saas provider of a Customer Data Platform and marketing automation software.
https://www.whiterabbitsuite.com/

Add White Rabbit source

---

organizations/salesmate.json
sources/salesmate.json

Added datasource to data registry

Added datasource to data registry

---

sources/foo.json

Adds [Foo](https://www.foo.software/) **source**.

Add Foo source

---

organizations/zoho.json
sources/zoho_crm.json

Adding Zoho to organization and Zoho CRM to sources

Add Zoho and Zoho CRM

---

amazon_ads.json

I have added Amazon Advertising Source.

Added Amazon Advertising Source

---

organizations/getontop.json
sources/calltracking.json

Added get on top to organizations and CallTracking to sources

Added get on top to organizations and CallTracking to sources

---

organizations/afas.json
sources/afas_profit.json

add AFAS Profit

---

organizations/socialinsider.json
sources/socialinsider.json

Added Socialinsider organization and source as a prerequisite for publishing a Community Connector for Google Data Studio.

Added Socialinsider organization and source

---

organizations/adriver.json

Add new organization for publishing new connector

Add new organization

---

sources/adriver.json

Add new source for publishing new connector

Add new source

---

organizations/wave.json
sources/waveapps.json

I want to add new organization Wave and new source WaveApps
Could you please merge the code?
(I will soon publish a data studio connector)

Add new organization Wave and new source WaveApps

---

organizations/backtracks.json

Add `BACKTRACKS` to organizations.

feat: add backtracks to organizations

---

organizations/ghoststead.json
sources/ghoststead.json

Add an organization and source for GhostStead (https://www.ghoststead.com/)

GhostStead org and source

---

sources/google_cloud_spanner.json

Signed-off-by: Tejpald3v <tejpal@d3vtech.com>
We are fetching the data from our Google Cloud Spanner database, which is the source for custom community connector that we have built for users.

Added google cloud spanner as a source file

---

organizations/tadabase.json
sources/tadabase.json

Added Tadabase Source

---

organizations/knack.json
sources/knack.json

Add Knack org and source

---

organizations/dataforseo.json
sources/dataforseo.json

add DataForSEO organization and source

add DataForSEO

---

sources/google_tables_area120.json

Add a source for Google Tables by Area 120

Tables source

---

organizations/marketing_bi.json
sources/affilbox.json

I want to add new organization Marketing.bi and new source Affilbox
Could you please merge the code?

Add new source Affilbox and organization marketing.bi

---

organizations/smartsheet.json
sources/smartsheet.json

Add smartsheet to org and sources

Add smartsheet to org and sources

---

organizations/agendor.json
organizations/currency_conversion.json
sources/agendor.json
sources/currency_conversion.json

These two are about an conector named Agendor and another named Currency Converter

Itens about two conectors.

---

organizations/viu.json
sources/matomo.json

Adding Matomo Data Source to provide a Data Studio Connector for Matomo Analytics (https://matomo.org/)

Add Matomo to Sources

---

organizations/ontraport.json
sources/ontraport.json

Hi @pfrisella ! I've added Ontraport organization. Please review. Thanks!

Added Ontraport

---

sources/google_calendar.json
sources/google_contacts.json
sources/google_tasks.json

Added Google Calendar, Tasks and Contacts to the sources

Added Google Calendar, Tasks and Contacts

---

organizations/iqm.json
sources/iqm_reporting.json

Hi,
Please add the IQM Corporation organization and data source iqm.json and iqm_reporting.json so that we could continue to publish our Data Connector for the Data Studio.
Thank you.

Adding IQM Corporation data source and organization

---

organizations/meisterplan.json
sources/meisterplan.json

- add Meisterplan organization
- add Meisterplan source

Add Meisterplan organization and source

---

organizations/vashkpi.json
sources/kpi_indicators.json
sources/vashkpi.json

- added company
- added source

adding company and source

---

organizations/gmo_internet.json
sources/makeshop.json

Adding Makeshop Data Source to provide a Data Studio Connector for Makeshop eCommerce Platform (https://www.makeshop.jp/)

Add Makeshop Source

---

organizations/notion.json
sources/notion.json

Add source and organization files for [Notion](http://notion.so).

feat: add notion source and organization

---

organizations/hubstaff.json
sources/hubstaff.json

Adding Source and Org for Hubstaff

Source and Org for Hubstaff

---

organizations/ahrefs.json
organizations/hinta.json
organizations/impact.json
organizations/linkwise.json
sources/hinta.json
sources/impact.json
sources/linkwise.json
sources/sizmek_advertising_suite.json

* adds **Sizmek** Advertising Suite source
* adds **Linkwise** source and organization
* adds **Impact** source and organization
* adds **Hinta** source and organization
* adds missing **Ahrefs** organization

Add data sources

---

organizations/perinity.json
sources/perinity.json

Adding sources for pernity grc connector

Pernity GRC Connector

---

organizations/topvisor.json

Please add Topvisor to organizations

Add topvisor.json

---

sources/optmyzr.json

Request to update the icon url

Request to update the icon url

---

sources/google_search_ads_360.json

This is a pull request to add a data source for Google Ads 360

Google Ads 360 source

---

organizations/sharp_spring.json
sources/sharp_spring.json

This is a new source for data connecting to sharpspring marketing and crm api.

Added new source sharpspring

---

organizations/whitebox.json
sources/whitebox.json

WhiteBox API is an internal project created to ingest data from internal APIs for internal usage. I would like to include this source in the Gallery in order to share this with other coworkers

add whitebox api source

---

organizations/odyssey_bv.json
sources/odyssey_attribution.json

Add Odyssey data source

---

organizations/eulerian.json
sources/eulerian_analytics.json

Integrate Eulerian Analytics as a DataSource for Google Data Studio

Integrate Eulerian Analytics as a DataSource for Google Data Studio

---

organizations/serprobot.json
sources/serprobot.json

Added serprobot.json files in the organizations and sources folders

Add serprobot organization and source

---

organizations/jivrus.json
sources/appiworks.json
sources/zoho_projects.json

Adding Zoho Projects as a source so that we can add a Data Studio Connector for it

Adding Zoho Projects from Zoho and AppiWorks from Jivrus

---

organizations/ynab.json
sources/ynab.json

Second try doing this, but should be better now. Thanks!

added YNAB organization and source

---

organizations/bitrix24.json
sources/bitrix24.json

Good day. We would like to publish our own Bitrix24 BI-connector on Google Data Studio marketplace. So we need to change some info here. Our new vendor made and official BI-connector is described here: https://helpdesk.bitrix24.com/open/15040862/

Changes to an info about Bitrix24

---

organizations/surveymonkey.json
sources/google_classroom.json
sources/surveymonkey.json

Adding SurveyMonkey source and organization

Adding SurveyMonkey

---

organizations/comeen.json
sources/comeen.json

Add [Comeen](https://getcomeen.com/) organization and source

Add comeen source

---

organizations/dooblo.json
sources/surveytogo.json

Add SurveyToGo data source to data registry

Add SurveyToGo data source to data registry

---

organizations/surveysparrow.json
sources/surveysparrow.json

Added org and source for SurveySparrow

Added SurveySparrow

---

organizations/dqoai.json
sources/dqoai_alerts.json

Please add DQO.ai Data Quality Alerts source and DQO.ai organization.

DQO.ai alerts source and DQO.ai organization added.

---

organizations/bling.json
sources/bling.json

Adding Bling(a brazilian ERP) as a source to be used by a datastudio connector

add Bling as a source for a community datastudio connector

---

organizations/deputy.json
sources/deputy.json

Adding Deputy Source and Organization

Adding Deputy Source and Organization

---

organizations/wrike.json
sources/wrike.json

Adding wrike source and organization

Wrike source and org

---

organizations/cratejoy.json
sources/cratejoy.json

Adding Cratejoy org and source

Adding Cratejoy

---

organizations/code7.json
sources/c7source

Adding source file to have a compability

Add code7 compability#2

---

organizations/kentico.json
sources/kentico.json

Adds data for the approval of the Kentico Xperience Partner Connector at https://github.com/Kentico/xperience-google-datastudio

Kentico Xperience connector

---

organizations/gavagai.json
sources/gavagai_explorer.json

Add Gavagai as valid organization and gavagai_explorer as a valid source.

Add gavagai organization and gavagai_explorer source

---

categories.json
organizations/kanbanize.json
sources/kanbanize.json

Please add Kanbanize source and org and Project Management category

Kanbanize patch 1

---

organizations/unmetric.json
sources/unmetric.json

Add unmetric org and source

---

organizations/accelo.json
sources/accelo.json

add accelo organization and resource files

add accelo org and source

---

organizations/usabilla.json
sources/usabilla.json

Add usabilla org and source

---

organizations/adbook.json
sources/adbook.json

Add adbook org and source

---

organizations/active_agent.json
sources/active_agent.json

Add active_agent org and source

Add active_agent org and source

---

organizations/tableau.json
sources/tableau.json

- Add Tableau organization
- Add Tableau source

Add Tableau organization and Tableau source

---

organizations/quickin.json
sources/quickin.json

[Added the new Quickin source and organization to the repository](https://github.com/googledatastudio/ds-data-registry/pull/955)

 Added Quickin source and organization

---

organizations/adthena.json
sources/adthena.json

I added a new data source and organization for Adthena (https://www.adthena.com/) to be able to build a community data connector.

Added Adthena source and organization.

---

organizations/experience.json
sources/experience.json

add Experience organization
add Experience source

Add Experience organization and Experience source

---

organizations/appnalysis.json
organizations/hashtaglabs.json
sources/appnalysis.json
sources/htlexec.json
sources/opa_suite.json

Added Appnalysis as a data source and organization.

Add Appnalysis data source and organization

---

sources/yoom.json

Added YoomDatabase as a data source

add yoom database source

---

organizations/meta.json

Adds Meta as an organization to organizations.

Add Meta to organizations

---

organizations/mint.json
sources/mint.json

Added Mint as a data source and organization

Added Mint as a data source and organization

---

sources/linkedin_business_manager.json

Add LinkedIn Business Manager source to Google Data Studio's ds-data-registry

Add LinkedIn Business Manager source

---

sources/snapchat_marketing.json

- Add Snapchat Marketing source

Add Snapchat Marketing source

---

organizations/databricks.json
sources/databricks.json

Adding Databricks org and source.

Adding Databricks

---

organizations/daxrm.json
sources/daxrm.json

Added DAXRM Organization and Source

Added DAXRM Organization and Source

---

organizations/intercom.json
sources/intercom.json

- Add Intercom organization and source

Add Intercom organization and source

---

organizations/dashzoom.json
sources/oeeboxdashzoom.json

Add Dashzoom org and OEE Box Dashzoom data source.

Add OEE Box Dashzoom org and source.

---

sources/fathom_analytics.json

Source file for Fathom Analytics

Add fathom_analytics.json Source

---

organizations/dynomapper.json
sources/dynomapper.json

Add DYNO Mapper organization and source

Add DYNO Mapper organization and source

---

sources/tiktok_ads.json

Add TikTok Ads source

---

organizations/kwai.json
sources/kwai.json

Added Kwai as a new organization and source to ds-data-registry.

Add Kwai as organization and source

---

organizations/datadog.json
sources/datadog.json

adds datadog source and organization

add datadog source and organization

---

organizations/hotjar.json
sources/hotjar.json

Add Hotjar organization and source to Google's Data Studio registry of data sources.

Add Hotjar organization and source

---

sources/confluence.json

confluence

---

4d.json
sources/qodly.json

Add 4D to organizations and Qodly to sources

Add 4D Organization and Qodly source

---

organizations/lazada.json
sources/lazada.json

Add Lazada organization and source to the registry.

Add Lazada organization and source

---

sources/growthplatform.json

Create growthplatform source

---

categories.json
organizations/fillout.json
sources/fillout.json

add fillout categorie, source and organization

---

sources/datastore

Hi Team, please add datastore as a source. I have added required details. Please check.

Create datastore Source

---

organizations/marcode.json
sources/marcode.json

Adds Marcode (an advertising insights platform) as an organisation and source

Add Marcode organisation + Source

---

organizations/threads.json
sources/threads.json

Add Threads organization and source to repository.

Add Threads organization and source

---

sources/thread.json

Spyder add new source thread.json

add new source :thread.json

---

categories.json
organizations/deepseek.json
organizations/openai.json
sources/ChatGPT.json
sources/deepseek.json

Add deepseek api as source and organisation, and added new category for Artificial Intelligence.

Add deepseek api source

---

organizations/openai.json
sources/ChatGPT.json

Added OpenAI API as a source and as an organisation

Added OpenAI API as a source

---

organizations/shopee.json
sources/shopee.json

Add Shopee organization and source to ds-data-registry.

Add Shopee organization and source

---

organizations/intellikid_systems.json
sources/intellikid_systems.json

Add IntelliKid Systems as Organization and Source for Looker Studio Connector.

Add IntelliKid Systems as Organization and Source

---

organizations/shopware.json
sources/shopware.json

adding Shopware as a data source for Looker Studio connector

Add shopware source

---

sources/amazon_athena.json

Add Amazon Athena source configuration

Add Amazon Athena source

---

organizations/mangools.json
sources/mangools.json

This PR adds Mangools to the Data Studio data registry as a new data source.
Mangools is a suite of easy-to-use SEO tools trusted by marketers worldwide. This integration will allow users to connect their Mangools data with Looker Studio and visualize key SEO metrics more effectively.
Contributor: Lukas Sekerak, CTO at Mangools.
Let me know if anything needs to be updated. Thanks!
https://mangools.com
Contact email: lukas.sekerak@itrinity.com

Added mangools.com as a new data source

---

organizations/jestor.json
sources/jestor.json

Created 2 new JSON files (source and organizations) to Jestor data connector

New Jestor source and organizations

---

organizations/clubspeed.json
organizations/onfleet.json
sources/clubspeed.json
sources/onfleet.json

Onfleet fleet management and customer servicing tool https://onfleet.com/

New SRC - onfleet

---

organizations/owox.json
sources/owox_data_mart.json

Add OWOX org and OWOX Data Mart source to the registry.

Add OWOX org and OWOX Data Mart source
